export const reducerCases = {
    SET_MESSAGES : "SET_MESSAGES",
    SET_SOCKET : "SET_SOCKET",
    SET_ONLINE_USERS : "SET_ONLINE_USERS",
    ADD_MESSAGE : "ADD_MESSAGE",
    SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
    SET_ROOMS : "SET_ROOMS",
    ADD_ROOM : "ADD_ROOM",
    SET_ROOM_SEARCH: "SET_ROOM_SEARCH",
    SET_CURRENT_ROOM : "SET_CURRENT_ROOM",
    SET_CURRENT_ROOM_ID: "SET_CURRENT_ROOM_ID",
    SET_TOTAL_UNREAD_MESSAGES: "SET_TOTAL_UNREAD_MESSAGES",
}